[package]
name = "teevee"
version = "0.0.3"
authors = ["Thomas Locher"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2"
chrono = "0.4"
